### ISSUE TITLE
环境部署

### ISSUE THREAD

**Issue by CZD-MO** [1161678627/face_detection_and_recognition_yolov5#2]
您好，请问能发下您的的环境部署吗？

**Comment by duckzhao** [comment]
> 您好，请问能发下您的的环境部署吗？

你好，抱歉我在外出，无法及时给你分享项目环境。
该项目分为server端和client端
1. 服务端需要配置①yolov5的基础环境，你可以参照yolov5的requirements.txt进行配置；②需要安装用作数据通讯的fastapi及uvicorn库，使用pip安装最新版本即可。
2. 客户端仅需要安装opencv和requests的最新版本即可。
你可以参照readme进行配置。
如果该项目对你有帮助的话请star它，谢谢。
